import { ArrowLeft, ExternalLink, RefreshCw } from 'lucide-react'
import type { Asset, Report } from '../types'
import { coinGlass, price, percent, safeUrl, statusLabel, summaryLabels, time } from '../lib/format'
export function StrategyDetail({ asset, report, busy, error, back, refresh }: { asset: Asset; report?: Report; busy: boolean; error?: string; back: () => void; refresh: () => void }) {
 const s = report?.strategy
 return <section className="detail-page">
 <div className="section-head"><button className="text-button" onClick={back}><ArrowLeft size={17} />全部标的</button><button disabled={busy} onClick={refresh}><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? '更新中' : '刷新策略'}</button></div>
 <div className="detail-title"><div><small>{asset.exchange} · {asset.currency}</small><h2>{asset.symbol}<span>{asset.name}</span></h2></div><div className="quote-large"><strong>{price(report?.quote.price)}</strong><span className={(report?.quote.change_pct || 0) < 0 ? 'negative' : 'positive'}>{percent(report?.quote.change_pct)}</span><small>行情时间 {time(report?.quote.as_of)}</small></div></div>
 {error && <p className="error" role="alert">{error}</p>}
 {!report ? <div className="empty">{busy ? '正在获取最新数据…' : '尚未生成策略，点击刷新开始。'}</div> : <>
 <article className="execution"><div className="section-head"><h3>执行策略</h3><span className={'badge ' + s?.direction_code.toLowerCase()}>{s?.direction}</span></div><p>{s?.timing || report.timing}</p><dl className="execution-levels"><div><dt>入场区间</dt><dd>{price(s?.entry_low)} – {price(s?.entry_high)}</dd></div>{(['tp1', 'tp2', 'tp3', 'stop_loss'] as const).map((key, i) => <div key={key}><dt>{i === 3 ? '止损 SL' : '止盈 TP' + (i + 1)}</dt><dd>{price(s?.[key])}</dd></div>)}</dl><p className="condition">{s?.condition}</p><small>生成时间 {time(report.generated_at)} · 数据完整度 {report.completeness?.score ?? '—'}% · 模型评分 {s?.confidence ?? '—'}（非胜率）</small></article>
 <h3 className="section-label">为什么这样给策略</h3><div className="summary-grid">{Object.entries(summaryLabels).map(([key, label]) => <article key={key}><small>{label}</small><p>{report.summary?.[key] || '数据不可验证，因此不参与本次判断。'}</p></article>)}</div>
 <h3 className="section-label">分析依据</h3><div className="evidence-list">{report.modules?.map((module, index) => <article key={index}><div className="section-head"><h3>{module.title}</h3><small className="badge wait">{statusLabel(module.status)}</small></div><p>{module.summary}</p>{module.details?.length ? <ul>{module.details.map((line, i) => <li key={i}>{line}</li>)}</ul> : null}{module.title.includes('流动性') && <div className="source-actions"><p>价格结构估算与股票永续清算数据分别展示；外部链接用于复核。</p>{coinGlass[asset.symbol] ? <a href={coinGlass[asset.symbol]} target="_blank" rel="noopener noreferrer">{asset.symbol} · CoinGlass <ExternalLink size={14} /></a> : <small>该标的暂无已核验的 CoinGlass 对应页面。</small>}</div>}</article>)}</div>
 <div className="sources-panel"><h3>数据来源与时间</h3>{report.sources?.map((source, i) => <div className="source-row" key={i}>{safeUrl(source.url) ? <a href={safeUrl(source.url)} target="_blank" rel="noopener noreferrer">{source.name}<ExternalLink size={13} /></a> : <span>{source.name}</span>}<small>{statusLabel(source.status)} · {time(source.as_of)}</small></div>)}<div className="source-actions"><a href={'https://finance.yahoo.com/quote/' + encodeURIComponent(asset.symbol) + '/'} target="_blank" rel="noopener noreferrer">{asset.symbol} 行情与新闻 <ExternalLink size={14} /></a>{asset.options_supported && <a href={'https://www.cboe.com/delayed_quotes/' + encodeURIComponent(asset.symbol) + '/quote_table'} target="_blank" rel="noopener noreferrer">期权链 <ExternalLink size={14} /></a>}</div></div>
 {report.warnings?.length ? <details className="limitations"><summary>数据限制与风险 · {report.warnings.length}</summary><ul>{report.warnings.map((line, i) => <li key={i}>{line}</li>)}</ul></details> : null}
 </>}</section>
}
